apiVersion: apps/v1
kind: Deployment
metadata:
  name: final-proj-dpy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: final-proj-pod
  template:
    metadata:
      labels: 
        app: final-proj-pod
    spec:
      containers:
        - name: final-proj-cnt
          image: faisalsouz/finalproj-tomcat:latest
          ports:
            - containerPort: 8080
