---
- name: Pull Docker Image on Remote Server
  hosts: dev
  tasks:
    # - name: Ensure Docker is installed
    #   apt:
    #     name: docker.io
    #     state: present

    # - name: Ensure Docker service is running
    #   service:
    #     name: docker
    #     state: started
    #     enabled: yes

    - name: Pull Docker image from Docker Hub
      community.docker.docker_image:
        name: faisalsouz/finalproj-tomcat
        tag: latest
        source: pull
