---
- name: Build and run Docker container
  hosts: docker-host
  tasks:
    - name: Build Docker image
      community.docker.docker_image:
        path: ABCTechnologies/Dockerfile
        name: faisalsouz/finalproj-tomcat
        tag: v1

    - name: Run Docker container
      community.docker.docker_container:
        name: faisalsouz/finalproj-tomcat
        image: yfaisalsouz/finalproj-tomcat:v1
        state: started
        ports:
          - "8090:8080"
