---
- name: Deploy application on Kubernetes
  hosts: dev
  tasks:
    - name: Clone the repository
      ansible.builtin.git:
        repo: "https://github.com/Faisalsouz/IndustryGradeProjectI-JavaProject.git"
        dest: /root/final-proj
        version: main
        force: yes

    - name: Apply pod manifest
      ansible.builtin.shell: |
        kubectl apply -f /root/final-proj/deployment-files/pod.yml
      args:
        chdir: /root/final-proj/deployment-files

    - name: Apply service manifest
      ansible.builtin.shell: |
        kubectl apply -f /root/final-proj/deployment-files/service.yml
      args:
        chdir: /root/final-proj/deployment-files

    - name: Apply deployment manifest
      ansible.builtin.shell: |
        kubectl apply -f /root/final-proj/deployment-files/deployment.yml
      args:
        chdir: /root/final-proj/deployment-files
