---
- name: Deploy application on Kubernetes
  hosts: dev
  tasks:
    - name: Clone the repository
      ansible.builtin.git:
        repo: "https://github.com/Faisalsouz/IndustryGradeProjectI-JavaProject.git"
        dest: /root/final-proj
        version: main
        force: yes

    - name: Create Kubernetes resources
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '/root/final-proj/deployment-files/pod.yml') }}"

    - name: Create Kubernetes service
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '/root/final-proj/deployment-files/service.yml') }}"

    - name: Create Kubernetes deployment
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '/root/final-proj/deployment-files/deployment.yml') }}"
