apiVersion: v1
kind: Service
metadata:
  name: final-proj-svc
spec:
  type: NodePort
  selector:
    app: final-proj-pod
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001
